language: ruby
rvm:
- 2.0.0
script: bundle exec rspec spec
services: mongodb
deploy:
  provider: heroku
  api_key:
    secure: mif3W/hD/BCP8v1WG+HPS2rNCzACmf55rnfWHldDltvXCY3T42aviwV+nOTqe2oDyd9PNoc6/wlbkpAXyaV2HVT2ZTYpLgb6YCGG1LJqnWSvcTLQNCQ3vh9vZ0Pu4YSNThNd9ulEJM2ATKSiC+ySFHoIwvoWT2gOCTRx2os+Hl0=
  app: volary-mockingbird-staging
  on:
    repo: VolaryFoundation/MockingBird
    ruby: 2.0.0
branches:
  only:
  - master
notifications:
  email:
    recipients:
    - nick@volary.org
    - lorne@volary.org
    - brendan@volary.org
    - michael@volary.org
    on_success: change
    on_failure: always
